services:
  - type: web
    name: aingefv-api
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: aingefv-db
          property: connectionString

databases:
  - name: aingefv-db
    plan: free
    region: frankfurt
    databaseName: aingefv
    user: aingefv
